import Head from 'next/head'
import SearchBar from '../components/SearchBar'
import Table from '../components/Table'


export default function Home() {
  return (
    <div>
      <Head>
        <title>ATD Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Table />
      </main>
    </div>
  )
}
